### ISSUE TITLE
Font in wrong directory

### ISSUE THREAD

**Issue by insperatum** [giorgi94/django-editor-widgets#3]
[skin.mobile.min.css](https://github.com/giorgi94/django-editor-widgets/blob/master/djangoeditorwidgets/static/tinymce/skins/ui/oxide-dark/skin.mobile.min.css) references `fonts/tinymce-mobile.woff`, but there is no `fonts` directory

**Comment by giorgi94** [comment]
Hi Luke, sorry for late response. I currently working on some projects, and couldn't check the code. I turn off mobile skin, since it is not as good as desktop, and maybe this is why I missed adding this font. plus in django you can easy override any static file, so I don't think adding it for now. 

Thank you for noticing it.

**Comment by insperatum** [comment]
Hey thanks for replying! And no worries -- I ended up forking this repo for my project anyway, so not a problem for me 👍

But fyi, the reason this is an issue is that if you `collectstatic` with Whitenoise (as per [Heroku's recommendation](https://devcenter.heroku.com/articles/django-assets#whitenoise)) it throws an error during compilation when it can't find the file. So this repo can't be included as a dependency.
